name: Telxl Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Ensure browsers are installed
      run: python -m playwright install --with-deps
    - name: Run you tests
      env: 
          CUSTNAME : ${{ env.CUSTNAME }}
          RESELLERNAME : ${{ env.RESELLERNAME }}
          CUSTPASSWORD : ${{ secrets.CUSTPASSWORD }}
          RESELLERPASSWORD : ${{ secrets.RESELLERPASSWORD }}
      run: python -m pytest --tracing=retain-on-failure --html=test-results/playwright.html
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-traces
        path: test-results/
